name: aplikasitest1
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - lib/assets/Rafi-1.png
    - lib/assets/Rafi-2.png
    - lib/assets/Rafi-3.png
    - lib/assets/hero-1.jpeg
    - lib/assets/hero-2.jpeg
    - lib/assets/hero-3.jpeg
    - lib/assets/hero-4.jpeg
    - lib/assets/hero-5.jpeg

